package nl.windesheim.kbs1.tzt_pakketten.view.main;

import nl.windesheim.kbs1.tzt_pakketten.datamanager.DataManager;
import nl.windesheim.kbs1.tzt_pakketten.datamanager.models.customer.Customer;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Wilco Wolters
 */
public class CustomersPanel extends javax.swing.JPanel {

    private DefaultListModel<Customer> listModel = new DefaultListModel<>();

    /**
     * Creates new form CustomersPanel
     */
    public CustomersPanel() {
        initComponents();
        DataManager.getInstance().getCustomers((success, data) -> {
            if (success) {
                listModel.removeAllElements();
                data.forEach(listModel::addElement);

            }
        });
        customerList.setModel(listModel);
        customerList.setCellRenderer(new CustomerRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane scollPane = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList();

        customerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scollPane.setViewportView(customerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Customer> customerList;
    // End of variables declaration//GEN-END:variables

    private static class CustomerRenderer extends DefaultListCellRenderer {

        private static final String CUSTOMER_FORMAT = "%03d - %s";

        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (component instanceof JLabel && value instanceof Customer) {
                ((JLabel) component).setText(String.format(CUSTOMER_FORMAT, ((Customer) value).getId(), ((Customer) value).getName()));
            }
            return component;
        }
    }
}
