package nl.windesheim.kbs1.tzt_pakketten.view.main;

import nl.windesheim.kbs1.tzt_pakketten.datamanager.DataManager;
import nl.windesheim.kbs1.tzt_pakketten.datamanager.models.customer.Customer;
import java.util.List;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Wilco Wolters
 */
public abstract class ListPanel<T> extends javax.swing.JPanel {

    private DefaultListModel<T> listModel = new DefaultListModel<>();
    private Renderer<T> renderer;

    public ListPanel() {
        this(t -> t == null ? "null" : t.toString());
    }

    /**
     * Creates new form ListPanel
     */
    public ListPanel(Renderer<T> renderer) {
        this.renderer = renderer;
        initComponents();
        customerList.setModel(listModel);
        customerList.setCellRenderer(new TRenderer());
    }

    protected void setElements(List<T> elements) {
        listModel.removeAllElements();
        elements.forEach(listModel::addElement);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane scollPane = new javax.swing.JScrollPane();
        customerList = new javax.swing.JList();

        customerList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scollPane.setViewportView(customerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList customerList;
    // End of variables declaration//GEN-END:variables

    private class TRenderer extends DefaultListCellRenderer {
        @Override
        public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            if (component instanceof JLabel) {
                ((JLabel) component).setText(renderer.getRenderString((T) value));
            }
            return component;
        }
    }

    public interface Renderer<T> {
        String getRenderString(T object);
    }
}
