package nl.windesheim.kbs1.tzt_pakketten.view.overview;

/**
 *
 * @author Wilco
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane jTabbedPane2 = new javax.swing.JTabbedPane();
        customerPanel1 = new nl.windesheim.kbs1.tzt_pakketten.view.overview.CustomerPanel();
        trainCourierPanel1 = new nl.windesheim.kbs1.tzt_pakketten.view.overview.TrainCourierPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.addTab("Klanten", customerPanel1);
        jTabbedPane2.addTab("Treinkoeriers", trainCourierPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private nl.windesheim.kbs1.tzt_pakketten.view.overview.CustomerPanel customerPanel1;
    private nl.windesheim.kbs1.tzt_pakketten.view.overview.TrainCourierPanel trainCourierPanel1;
    // End of variables declaration//GEN-END:variables
}
